### PR TITLE
Add CI to goal environment

### PR DESCRIPTION
**Pull request by spiderbiggen**
As a developer
I want to setup a Continuous integration setup
so that other developers can see that another developers code works

### CODE REVIEW

**Comment by tvleest** [comment]
Should be good for now. approved.

**Comment by MichielvdBerg** [comment]
Approved

**Comment by tvleest** [comment]
Looks a lot better now.
We'll probably need to update the test in the next few days when we enhance the agent.
Approved.

**Comment by MichielvdBerg** [comment]
Looks a lot better indeed. Please add a user story in the description and then it can be merged.

**Comment by spiderbiggen** [comment]
@MichielvdBerg As a developer
I want to setup a Continuous integration setup
so that other developers can see that another developers code works

**Pull request merged**
