### PR TITLE
Last fixes for demo

### PR DESCRIPTION
**Pull request by spiderbiggen**
this includes fixes to the buyland module and when to call it

As an agent When in a 
simulation I am able to buy 
ground if I think this is 
benificial for me. To construct 
things that are part of my goals.

### CODE REVIEW

**Comment by daanwerf** [comment]
Seems fine. I approve as i worked with you on it so i know what it does :)

**Comment by tvleest** [comment]
You're missing a user story.

**Comment by tvleest** [comment]
Approved.

**Comment by spiderbiggen** [comment]
As an agent i want to build on land i bought

**Pull request merged**
